[params]
length = 10_000 
# Length of the experiment in microseconds
cable_delay = [0.016, 0.002] 
# Cable delay in microseconds; given as [mu, sigma] normal distribution


[nic]
module = 'nic_default'
count = 1 
# Number of NICs
bandwidth = 1_000_000
# Output bandwidth in bytes per second
processing_time = [0.016, 0.002]
# Processing time in microseconds per 1000*byte; given as [mu, sigma] normal distribution


[host]
module = 'host_swift'
count = 100
# Number of hosts
bandwidth = 1_000_000
# Output bandwidth in bytes per second
processing_time = [0.016, 0.002]
# Processing time in microseconds per 1000*byte; given as [mu, sigma] normal distribution
lifetime = [0, 0]
# Interval of activity [start, end]. If 'start' == 'end', it lasts till the end of experiment
packet_size = 1_000
# Packet size in bytes
initial_cwnd = 10
# Initial Congestion Window size
